version: '3.9'

services:
  profilegrpc:
    build:
      context: .
      dockerfile: Dockerfileprofilegrpc
    restart: always
    ports:
      - "7074:7074"
    depends_on:
      - db
  authgrpc:
    build:
      context: .
      dockerfile: Dockerfileauthgrpc
    restart: always
    ports:
      - "7072:7072"
  project:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
  auth:
    build:
      context: .
      dockerfile: Dockerfileauth
    restart: always
    ports:
      - "8081:8081"
      - "7071:7071"
    depends_on:
      - redis
      - db
  file:
    build:
      context: .
      dockerfile: Dockerfilefile
    volumes:
      - ./image:/image
    restart: always
    ports:
      - "8082:8082"
  chat:
    build:
      context: .
      dockerfile: Dockerfilechat
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - postgres_data:/var/lib/postgresql/vk_app_data
    expose:
      - 5432
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    volumes:
      - ./redisdata:/data
    expose:
      - 6379
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    tty: true
    stdin_open: true
volumes:
  postgres_data: