global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:8080']
  - job_name: "main"
    metrics_path: /api/v1/metrics
    static_configs:
      - targets: ['project:8080']